server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.24.77:3306/hj?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 9YAYAjSwI2TW28iV
  data:
    redis:
      port: 6379
      host: localhost
  ai:
    openai:
      api-key: XGp4n1MJcLEJBIiVwXjHOJla

mybatis:
  configuration:
    map-underscore-to-camel-case: false  # 关闭驼峰命名



 # 自定义配置
wenxin:
  moxing: ERNIE-4.0-8K

custom-config:
  project:
    project-name: HJ
    version: 1.0







